### ISSUE TITLE
reorganize README template

### ISSUE THREAD

**Issue by robertcsapo** [CiscoSE/cc-pyscript#1]
There's so many repos on Github and you only have a limited time to attract users to your repo/project.

If you read through https://github.com/matiassingers/awesome-readme, many people suggest show/demo and running the script (in simple way) is important to get people onboard.

Today the README template is structured
* Motivation
* Show Me!
* Features
* Technologies & Frameworks Used
* Usage
* Installation
* Authors & Maintainers
* Credits
* License

Suggestion to reorganize README template this way
* Motivation
* Show Me!
* **Usage** _(suggestion)_
* **Installation** _(suggestion)_
* Features
* Technologies & Frameworks Used
* Authors & Maintainers
* Credits
* License

What do you think?

**Comment by cmlccie** [comment]
I'm with you.  Show me working code, the UX your project provides, and how I can quickly get started and I'm sold.

Want to submit a pull request?  Any tweaks to verbiage are welcome too.

**Comment by cmlccie** [comment]
My only reason for usage lower was that some people use this space in their README to put ***all*** of their usage documentation (most typically people creating CLI scripts) and this can be lengthy (many won't read past this).  The *Features* and *Technologies & Frameworks Used* sections should be very concise lists that give at-a-glance context for what you have created.

**Comment by robertcsapo** [comment]
I don't have preferred way of the README structure, but I personally find demo/show case more interesting when I'm viewing repos.

If you just want to move the template as I've suggested, then I could make a PR for that.
But I don't mind if other people have suggestions on this topic.
